// export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_TOP_STORIES = "FETCH_TOP_STORIES";
export const FETCH_NEWEST_STORIES = "FETCH_NEWEST_STORIES";
export const FETCH_BEST_STORIES = "FETCH_BEST_STORIES";
